# Generated by Django 5.1.6 on 2025-05-18 06:33

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='drivers',
            managers=[
                ('for_company_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
