# Generated by Django 5.1.6 on 2025-05-18 06:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0002_alter_drivers_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='drivers',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='vehicle',
            managers=[
                ('for_company_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
